# Generated by Django 5.0.3 on 2024-03-06 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enterprise', '0002_remove_devicelog_device_id_remove_devicelog_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('Device_ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('deviceModel', models.CharField(max_length=255)),
                ('Enterprise_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.enterprise')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceLog',
            fields=[
                ('DeviceLog_ID', models.AutoField(primary_key=True, serialize=False)),
                ('checkoutTime', models.CharField(max_length=50)),
                ('checkoutDate', models.CharField(max_length=50)),
                ('checkoutMonth', models.CharField(max_length=10)),
                ('checkinTime', models.CharField(max_length=50)),
                ('checkinDate', models.CharField(max_length=50)),
                ('checkinMonth', models.CharField(max_length=10)),
                ('Device_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.device')),
            ],
        ),
    ]
