# Generated by Django 5.0.3 on 2024-03-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_devicequerymanager_device_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicelog',
            name='checkinConditionDevice',
            field=models.CharField(default='OK', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicelog',
            name='checkoutConditionDevice',
            field=models.CharField(default='OK', max_length=255),
            preserve_default=False,
        ),
    ]
