# Generated by Django 5.0.3 on 2024-03-06 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('Enterprise_ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('Device_ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('deviceModel', models.CharField(max_length=255)),
                ('Enterprise_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.enterprise')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('User_ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('Enterprise_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.enterprise')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceLog',
            fields=[
                ('DeviceLog_ID', models.AutoField(primary_key=True, serialize=False)),
                ('checkoutTime', models.CharField(max_length=50)),
                ('checkoutDate', models.CharField(max_length=50)),
                ('checkoutMonth', models.CharField(max_length=10)),
                ('checkinTime', models.CharField(max_length=50)),
                ('checkinDate', models.CharField(max_length=50)),
                ('checkinMonth', models.CharField(max_length=10)),
                ('Device_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.device')),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.user')),
            ],
        ),
    ]
