# Generated by Django 5.0.3 on 2024-03-06 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicelog',
            name='Device_ID',
        ),
        migrations.RemoveField(
            model_name='devicelog',
            name='User_ID',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Enterprise_ID',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='DeviceLog',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
